-   id: build-docs
    name: Build Sphinx Docs
    description: This pre-commit hook builds docs using sphinx, and should fail if a syntax error exists in the docs
    require_serial: true # Serial execution so that other routines that alter docs (e.g. formatting in python code samples) don't conflict.
    language: python
    entry: build-docs
-   id: convert-bibliography
    name: Convert Bibliography
    description: This pre-commit hook converts a BibTeX .bib file to a .rst citations file.
    language: python
    entry: convert-bibliography